name: TEST

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type checking
        run: pnpm run typecheck

  quality:
    name: Code Quality Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  test-and-coverage:
    name: Test and Coverage
    runs-on: ubuntu-24.04
    needs:
      - typecheck
      - quality

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests with coverage
        run: pnpm run test
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
